/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const { protodocs } = require('./docs/grpc/sidebar')
const datav2 = require('./docs/api/rest/data-v2/sidebar.js')
const datav1 = require('./docs/api/rest/data-v1/sidebar.js')
const core = require('./docs/api/rest/core/sidebar.js')
const state = require('./docs/api/rest/state/sidebar.js')

module.exports = {
  api: [
    'api/overview',
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials'
        }
      ]
    },
    /* {
      type: "category",
      label: "How-to guides",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "howto",
        },
      ],
    }, */
    {
      type: 'category',
      label: 'GraphQL',
      collapsed: true,
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'graphql/schema'
        },
        {
          type: 'autogenerated',
          dirName: 'graphql'
        }
      ]
    },
    {
      type: 'category',
      label: 'GRPC',
      items: [protodocs[0].items]
    },
    {
      type: 'category',
      label: 'REST',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'api/rest/overview',
          label: 'Overview'
        },
        datav2,
        datav1,
        core,
        state
        /*        {
          type: 'link',
          href: '/docs/testnet/api/rest/data-v1/trading-data-service',
          label: 'Data node (v1)'
        },
        {
          type: 'link',
          href: '/docs/testnet/api/rest/data-v2/trading-data-service',
          label: 'Data node (v2)'
        },
        {
          type: 'link',
          href: '/docs/testnet/api/rest/core/core-service',
          label: 'Core'
        },
        {
          type: 'link',
          href: '/docs/testnet/api/rest/state/core-state-service',
          label: 'Core state'
        } */
      ]
    },
    {
      type: 'category',
      label: 'Ethereum bridge',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/bridge'
        }
      ]
    },
    {
      type: 'category',
      label: 'Wallet API',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/vega-wallet'
        }
      ]
    }
  ],
  concepts: [
    {
      type: 'autogenerated',
      dirName: 'concepts'
    }
  ],
  tools: [
    {
      type: 'autogenerated',
      dirName: 'tools'
    }
  ],
  'node-operators': [
    {
      type: 'autogenerated',
      dirName: 'node-operators'
    }
  ]
}
